cstrike:
  build: ./
  environment:
    - SERVER_NAME="My cool server"
    - RCON_PW=""
    - START_MAP="de_dust2"
  ports:
    - "26900:26900/udp"
    - "27020:27020/udp"
    - "27015:27015/udp"
    - "27015:27015"
  volumes:
    - ./cstrike/liblist.gam:/steam/cs16/cstrike/liblist.gam
    - ./cstrike/addons:/steam/cs16/cstrike/addons
